version: '3'

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8088:80"
        volumes:
            - ./backend:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks:
            - laravel
    
    mysql:
        container_name: mysql
        image: mysql:5.7.22
        restart: unless-stopped
        tty: true
        networks:
            - laravel
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=Baly"
            - "MYSQL_USER=phpmyadmin"
            - "MYSQL_PASSWORD=phpmyadmin"
            - "MYSQL_ROOT_PASSWORD=finallyJDBC2017."
        ports:
            - 4306:3306
            
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./backend:/var/www/html
        ports:
            - "9000:9000"
        networks: 
            - laravel
        