version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3001:80"

  #  The Application
  app:
    container_name: laravel_app
    # build:
    #   context: ./backend
    #   dockerfile: development/app.dockerfile
    image: usmansabir98/laravel_app
    volumes:
      # - ./backend/storage:/var/www/storage
      - ./backend:/var/www
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"

  # The Web Server
  web:
    container_name: web
    build:
      context: ./backend
      dockerfile: development/web.dockerfile
    volumes:
      - ./backend/storage/logs/:/var/log/nginx
    ports:
      - 8990:80

  # The Database
  database:
    container_name: mysql_database
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=Baly"
      - "MYSQL_USER=phpmyadmin"
      - "MYSQL_PASSWORD=phpmyadmin"
      - "MYSQL_ROOT_PASSWORD=finallyJDBC2017."
    ports:
      - 8991:3306

    # redis
  cache:
    image: redis:3.0-alpine

  next:
    container_name: next
    build:
        dockerfile: Dockerfile.dev
        context: ./next
    volumes:
        - /usr/src/app/node_modules
        - /usr/src/app/.next
        - ./next:/usr/src/app

volumes:
  dbdata:
